### PR TITLE
[WIP] tether: add tether model and solo_with_tether for testing

### PR DESCRIPTION
**Pull request by TSC21**
This is my ongoing work for the dynamic model of the tether. Currently testing with a solo model IOT make sure it behaves naturally. I am still to find a way to stick it properly to the world, as it currently is moving with the vehicle. When that's fixed, the jump the the KiteX should be natural.
This comes with the tether force model you implemented, though I am not sure way isn't in your master.

### CODE REVIEW

**Comment by GabrielKoenig** [comment]
Hi Nuno
Thank you very much for the first draft of the tether. I just discussed it with Sebastian and he also think using the sdf model properties is the way to go instead of using the mathematical formulas. Its even nearer to a pyhsical tether. 
Let me list some remarks.

1. The following physical properties are missing (referring to the provided paper and matlab code) 
1.1 drag (direction and force) of the tether depending on the apparent airspeed and the tether diameter of each elements, it can be added either at the cylinder itself or the sphere (preferable on the cylinder). I would propose to use the lift /drag plug in and set the lift to zero.   
1.2 not only damping coefficients should be part of the dynamic model (please also add to the dynamics the spring reference and spring constant for each joint, all the same)

2. Improvements
2.1 as you probably also observed, it is quite hard to take off and land twice in a row. Thus I would propose to remove the collision block for all the elements (especially when the rope we might have undesired behaviour), or do you see an useful function for it? 
2.2 due to the same reason I think the damping coefficient is much to hight (when taking off the rope doesn’t aligned properly, see picture). Reducing it has much a nicer effect (e.g. 0.1)
2.3 its difficult to validate the tether if it is not fixed to the ground. Could you send as soon as possible a version where it is fixed?

3. The following points you haven’t yet implemented, but are defined as required. I assume they will be implemented in the final version, but let me list them anyways: 
3.1 Y tether in the end
3.2 “the initial length of the tether respectively the corresponding amount of spring/ mass elements
should be adaptable in the sense that it is independent from the distance between the home
position and the aircraft launch position.“ It is fine that the tether length is fixed, but the amount of joint elements needs to be adaptable by the user in advance. (the reason is, that we want to test how does a tether behave for the same tether length e.g. 250. of tether with 100 or only 10 joint elements.) Thus at the moment you have one big file with all the elements manually added depending on the tether length, thus setting the number of elements an setting the number of joints and sphere length by the user, should create the desired tether, which is fixed for the whole simulation. (see matlab code)
3.3 Tether force (at least of one joint element), tether length, tether reel out speed (for now speed=zero) needs to be published as a protobuf message and visualized somewhere in the gazebo simulation

4.Question:
4.1 Do you know the units used for the damping and spring constant coefficients? Where are those units specified? 
Cheers 
Gabriel 
screenshot from 2018-03-27 00-03-01
screenshot from 2018-03-27 18-42-26

**Comment by TSC21** [comment]
I will try to address point by point:
> 1.1 drag (direction and force) of the tether depending on the apparent airspeed and the tether diameter of each elements, it can be added either at the cylinder itself or the sphere (preferable on the cylinder). I would propose to use the lift /drag plug in and set the lift to zero.

Done in 8510b24, though I think the parameters can be optimized.

> 1.2 not only damping coefficients should be part of the dynamic model (please also add to the dynamics the spring reference and spring constant for each joint, all the same)

Done in d07139e.

> 2.1 as you probably also observed, it is quite hard to take off and land twice in a row. Thus I would propose to remove the collision block for all the elements (especially when the rope we might have undesired behaviour), or do you see an useful function for it?

Actually after the changes above, you can now properly land and takeoff without any problem and without removing the collision block.

> 2.2 due to the same reason I think the damping coefficient is much to hight (when taking off the rope doesn’t aligned properly, see picture). Reducing it has much a nicer effect (e.g. 0.1)

Done in d07139e.

> 2.3 its difficult to validate the tether if it is not fixed to the ground. Could you send as soon as possible a version where it is fixed?

Done in 8510b24.

> 3.1 Y tether in the end

Todo but it would be a easy add.

> 3.2 “the initial length of the tether respectively the corresponding amount of spring/ mass elements
should be adaptable in the sense that it is independent from the distance between the home
position and the aircraft launch position.“ It is fine that the tether length is fixed, but the amount of joint elements needs to be adaptable by the user in advance. (the reason is, that we want to test how does a tether behave for the same tether length e.g. 250. of tether with 100 or only 10 joint elements.) Thus at the moment you have one big file with all the elements manually added depending on the tether length, thus setting the number of elements an setting the number of joints and sphere length by the user, should create the desired tether, which is fixed for the whole simulation. (see matlab code)

Regarding this point - given that the tether length is going to be fixed, and in order that the number of elements is variable, I propose the approach used in https://github.com/PX4/sitl_gazebo/pull/37. Using jinja description, you can easily generate the model you want by just changing the number of elements you want to generate, that can be fed into a for loop for example (https://github.com/PX4/sitl_gazebo/blob/master/models/matrice_100/matrice_100.sdf.jinja#L131-L147). This would easily generate the model of the tether you want, and at the same time you could tune the parameters for the dynamics, drag etc. for each of the elements of the tether. The current problem it that your master branch is out of sync, so I would have to do a merge pull of the current `sitl_gazebo` master to work on this. Does this sounds good to you? If yes, please let me know so I can continue with this and that way I could add the Y element to it also.

> 3.3 Tether force (at least of one joint element), tether length, tether reel out speed (for now speed=zero) needs to be published as a protobuf message and visualized somewhere in the gazebo simulation

So you want something as a plugin that reports this data using a protobuf msg? My point of view is that writing this up would be the same as writing the base for the next phase of the project, which would only take to add a dynamic way of generating the elements on runtime (which I actually already know what to do). Can we push this to the next phase instead? Also, I am not actually sure how you want to *visualize somewhere in the gazebo simulation*.

> 4.1 Do you know the units used for the damping and spring constant coefficients? Where are those units specified?

For damping, check http://wiki.ros.org/urdf/XML/joint:
***damping** (optional, defaults to 0)*
*The physical damping value of the joint ...*

For the spring, I would guess that the `spring_stiffness` would be the same as the spring constant, based on the computation of the elastic potential energy [here](https://bitbucket.org/osrf/gazebo/src/bcfe9f8268cc32ec43bc57fe6374882c46ec02c8/gazebo/physics/Joint.cc?at=gazebo_4.1&fileviewer=file-view-default#Joint.cc-1125:1140), so it is N.m⁻¹ or kg.s⁻², given that the forces in Gazebo are in Newtons and the distances are in meters, while the `spring_reference` is the reference position where the spring compresses.

**Comment by TSC21** [comment]
@GabrielKoenig @xgerrmann I am still waiting for your feedback on this so I can move this forward.

**Comment by GabrielKoenig** [comment]
Hi Nuno
Sorry for the late reply. The taks from 1 - 2 are nice implemented. Regarding the open task:
We would like to make the intermediate step using jinja description. Before we use the fully dynamic model, we would like to investigate different configuration of joint length and number of joints as mentioned previously for fixed tether length. Could you therefore please do a merge pull with the master branch from the gazebo_sitl repo? 

Regarding the data (3.3), you could also add a force sensor to one of the end joints... (we just need always  to have the values printed out (within gazebo gui or console) for the tether length and tether_force (velocity can be kept out).

Cheers
Gabriel

**Comment by TSC21** [comment]
> Hi Nuno
>Sorry for the late reply. The taks from 1 - 2 are nice implemented. Regarding the open task:
We would like to make the intermediate step using jinja description. Before we use the fully dynamic model, we would like to investigate different configuration of joint length and number of joints as mentioned previously for fixed tether length. Could you therefore please do a merge pull with the master branch from the gazebo_sitl repo?
>
>Regarding the data (3.3), you could also add a force sensor to one of the end joints... (we just need always to have the values printed out (within gazebo gui or console) for the tether length and tether_force (velocity can be kept out).
>
>Cheers
>Gabriel

Let's continue on #2.

**Pull request closed without merging**
