### PR TITLE
WIP: Y element

### PR DESCRIPTION
**Pull request by TSC21**
This is becoming complex with time and it's taking more time than I have planned to take into this. In any case, here's the WIP. The current problem actually relies on the visual part of the Y element, rather than it's physical properties, as the visual elements tend to not mimic the position of the actual joint for some reason.
I am still working on the `solo` model cause it seemed simple to me to work on. I will add all the features you asked till the end of the weekend but I cannot promise that the visual part of it is going to be pretty, because the model is complex. If the actual physics of it work, I would be pretty happy.

### CODE REVIEW

**Comment by GabrielKoenig** [comment]
Thanks for the update. From pull/5 review I only see point Nr3, Nr7 properly implemented, the tether anchor point can properly be set. Nr 2 and Nr 8 are still open. (the others would have been a nice to have, but not a must). 

But it seems its not only the y theter that doesn't seems to work, also the main elements are not properly linked together. Setting 4 tether elements and 4m length, the drone is even not able to takeoff properly, thus It doesn't look like its only a visual thing (and also not only a y-element issue) : 
screenshot from 2018-06-03 13-03-26


Also if I choos smaller element length, it doesn't seem to link properly
screenshot from 2018-06-03 13-06-52

Also setting the anchor point x position to 3m, the y-element seems to stand anywhere: 
screenshot from 2018-06-03 13-16-54

Can you identify the error?

**Comment by TSC21** [comment]
I was actually fixing this. Can you please try last commit? Thanks @GabrielKoenig

**Comment by GabrielKoenig** [comment]
Okey main tether seems to be fixed. Thanks. 
Regarding the y tether, I realized that the visual of the y tether (resp. gap to the drone) is dependend on the elemnt length of the main tehter, which doesn't make sense. Thus still its not only visual as the drones position differes regarding the theter length elements. 

Possible workaround: don't define the y_el tether length element, but just the attachment position (as it is know) and the hight of the triangle (the length of the two elemts gets just computed).

**Comment by TSC21** [comment]
> Regarding the y tether, I realized that the visual of the y tether (resp. gap to the drone) is dependend on the elemnt length of the main tehter, which doesn't make sense. Thus still its not only visual as the drones position differes regarding the theter length elements.

I understand what you say but that's not possible to do. The reason is the following: or you set the tether visual depending on the drone spawn position, or you set the tether visual depending on the anchor point. You cannot do both because those are independent models (the tether and the vehicle). What you suggest is that I set the tether depending of the Y element attachment positions, but that would mean that the anchor points would depend on the attachment points also, because the visual of the tether, meaning the tether length, is also a parameter you tweak. So or you start in one end or you start in the other end, as they are conditioned by:
1. The tether elements length;
2. The anchor point;
3. The vehicle spawn point and respective attachments.

This is a constraint of the model itself and there's much we can do about it.

**Comment by TSC21** [comment]
And believe me: I spent hours around this trying to find the most suitable solution. Maybe it's not the perfect one, but it is the one I found that would work better for the constraints we have.

**Comment by TSC21** [comment]
> Possible workaround: don't define the y_el tether length element, but just the attachment position (as it is know) and the height of the triangle (the length of the two elements gets just computed).

I will check if this is possible.

**Comment by TSC21** [comment]
@GabrielKoenig I have found a workaround that basically fits the condition of having the Y element length depending on tether and the vehicle spawn point: in order to avoid the user to make a mistake with the vehicle spawn point, what I did was basically set a parameter which is the distance from the vehicle to the Y element attachments, which has to be greater or equal than the length of the tether elements. This way, the vehicle spawns at that location and the Y elements length is computed based on the XYZ attachment point coordinates.
Please have a go on the last commit.

**Comment by TSC21** [comment]
@GabrielKoenig I was trying to test this with the KiteX model but seems it's not available on the `PX4_Firmware` repo. Though I added the build targets for it there but it's probably out of sync with `PX4_KiteX`. Can @xgerrmann do a manual update of it into `PX4_Firmware` where it cherry picks is changes to there so it can be tested on `PX4_Firmware` branches? Unless you want to try it in `PX4_KiteX` but you will always have the problem we talked about about the build process.
Please have a go with the above changes. I think I have address all your requests. I tried to play with the inertial tensor values but with no luck. It may be a Gazebo problem and probably an update to it may solve it (to Gazebo 8 or 9), but I am not sure. Please let me know what else is left to do.

**Comment by TSC21** [comment]
BTW the working branch on `PX4_Firmware` is [`kitex_with_tether`](https://github.com/RigidWing/PX4_Firmware/tree/kitex_with_tether). I add the build targets there for `kitex` and `kitex_with_tether` but would be helpful if @xgerrmann could cherry pick is changes into there.

**Comment by TSC21** [comment]
@GabrielKoenig @xgerrmann this is ready to review. Take a look and test when you are able to. Thank you for your patience.

**Comment by GabrielKoenig** [comment]
>Regarding the y tether, I realized that the visual of the y tether (resp. gap to the drone) is dependend on the elemnt length of the main tehter, which doesn't make sense. Thus still its not only visual as the drones position differes regarding the theter length elements.

>>I understand what you say but that's not possible to do. The reason is the following: or you set the tether visual depending on the drone spawn position, or you set the tether visual depending on the anchor point. You cannot do both because those are independent models (the tether and the vehicle). What you suggest is that I set the tether depending of the Y element attachment positions, but that would mean that the anchor points would depend on the attachment points also, because the visual of the tether, meaning the tether length, is also a parameter you tweak. So or you start in one end or you start in the other end, as they are conditioned by:

>>The tether elements length;
The anchor point;
The vehicle spawn point and respective attachments.

>>This is a constraint of the model itself and there's much we can do about it.

Okey if we have those three options I would prefer the to make it dependen ont the 3rd point, the vehicle spawn point and respective attachments. Because my biggest issue at the moment is the constraint on the vehicle_to_attach_dist, which is implemented that you can not choose smaller value than the tether element lenght. See the figure, if I choose element length of 1meter, and vehicle_to_attach_dist to 0.2: 
screenshot from 2018-06-03 22-50-32

Thus, I would go for the 3rd option and place the vehicle always in the gazebo origin world and make the anchor point dependent on the tether parameters (resp. lengths) . (Would this solve the issue shown above?) Would this mean too much work for you or could you do this?

**Comment by GabrielKoenig** [comment]
>Possible workaround: don't define the y_el tether length element, but just the attachment position (as it is know) and the height of the triangle (the length of the two elements gets just computed).
>>I will check if this is possible.

Thanks for implementing it this way, perfect.

**Comment by GabrielKoenig** [comment]
>@GabrielKoenig I was trying to test this with the KiteX model but seems it's not available on the PX4_Firmware repo. Though I added the build targets for it there but it's probably out of sync with PX4_KiteX. Can @xgerrmann do a manual update of it into PX4_Firmware where it cherry picks is changes to there so it can be tested on PX4_Firmware branches? Unless you want to try it in PX4_KiteX but you will always have the problem we talked about about the build process.
Please have a go with the above changes. I think I have address all your requests. I tried to play with the inertial tensor values but with no luck. It may be a Gazebo problem and probably an update to it may solve it (to Gazebo 8 or 9), but I am not sure. Please let me know what else is left to do.

Yea we will take care for make it compatible with the KiteX firmware. @Xander and Andreas will take care. Don't worry.

**Comment by GabrielKoenig** [comment]
>@GabrielKoenig @xgerrmann this is ready to review. Take a look and test when you are able to. Thank you for your patience.

Thanks a lot for the work and also for implementing Nr 2, Nr 6 and Nr 8 and I am looking forward hearing from you regarding the last issue.

**Comment by TSC21** [comment]
> Thus, I would go for the second option and place the vehicle always in the gazebo origin world and make the anchor point dependent on the tether parameters (resp. lengths) . (Would this solve the issue shown above?) Would this mean too much work for you or could you do this?

This was actually my first approach and it was giving me more problems than this one. I think that this one is actually doing pretty good and it actually makes more sense to have the anchor point as the global origin of the combined model. As you can see, the only constraint is to have an acceptable distance between the vehicle and the tether so it can function properly, and that way you have the Y element dependent of both tether and attach points as you suggested. I could have just set the spawn point to be a fixed value and you wouldn't have any way of setting the Y element length - it would be always a fixed dependent value.

**Comment by TSC21** [comment]
> One last general question: To validate if the drag force is properly implemented, is it possible to visualize a force vector in real time within gazebo?

I think it is but I have not explored it. Is this still a requirement?

**Comment by GabrielKoenig** [comment]
> One last general question: To validate if the drag force is properly implemented, is it possible to visualize a force vector in real time within gazebo?

>>I think it is but I have not explored it. Is this still a requirement?

Not its not a requirement, as not specified in the work, but nice to have. If you can just give a hint, we can explore it ourselfe.

**Comment by GabrielKoenig** [comment]
>Thus, I would go for the second option and place the vehicle always in the gazebo origin world and make the anchor point dependent on the tether parameters (resp. lengths) . (Would this solve the issue shown above?) Would this mean too much work for you or could you do this?

>>This was actually my first approach and it was giving me more problems than this one. I think that this one is actually doing pretty good and it actually makes more sense to have the anchor point as the global origin of the combined model. As you can see, the only constraint is to have an acceptable distance between the vehicle and the tether so it can function properly, and that way you have the Y element dependent of both tether and attach points as you suggested. I could have just set the spawn point to be a fixed value and you wouldn't have any way of setting the Y element length - it would be always a fixed dependent value.

Mhmm okey, well if it caused more troubles  then I wouldn't go back. But is there an option to set the constraint smaller or equal than the tether element length?

**Comment by TSC21** [comment]
> Mhmm okey, well if it caused more troubles then I wouldn't go back. But is there an option to set the constraint smaller or equal than the tether element length?

I will think of a way without having to redo the all approach. But please consider that I have too much on my back now and I can't promise I will have a ready solution this week. If you could accept this PR, I will then add a new PR with the solution for this. Thanks

**Comment by GabrielKoenig** [comment]
> I will think of a way without having to redo the all approach. But please consider that I have too much on my back now and I can't promise I will have a ready solution this week. If you could accept this PR, I will then add a new PR with the solution for this. Thanks

Okey I will merge it tomorrow. Thanks for the suggestion to take a look later on.

**Pull request merged**
