### PR TITLE
Add Y element

### PR DESCRIPTION
**Pull request by TSC21**
This adds the Y element, with an element to the left and an element to the right, with the possibility of having a bigger length than the other elements.
I also fixed the bug with the last element.

### CODE REVIEW

**Comment by TSC21** [comment]
@xgerrmann just rebase and applied the modifications you asked. About the liftDragPlugin: is it physically logical to set the drag coefficient constant and independent of alpha?

**Comment by TSC21** [comment]
@xgerrmann @GabrielKoenig friendly ping.

**Comment by GabrielKoenig** [comment]
@TSC21 
Hi Nuno

Sorry for the late reply, now all exams and holidays are over ;) 

The following final feedback I have for you:
1. First of all: every time I run the tether sim, I get pleased even more about the nice implementation. Using jinja was the best decision :) 
2. Please change the current Y tether implementation. Please do not use angle, and element length as parameter, take instead coordinates of the two attachment point in the body reference frame of the aircraft and the high of the triangular of Y tether.  At the moment it is not properly implemented (see attached figure, when changing the element length  and number of elements (eg. 5elements and 3m length), the end of the tether and Y element is in the nowhere….)
3. Referring to 2 it would be desirable that we can also define the location of the anchor point within the set of tweakable parameters. Thus I was thinking of defining the two attachment point on the aircraft and defining the anchor point on the ground (preferably [0;0;0] in the world frame) as fixed input. The jinja generator would generate half of the tether away from the aircraft and come back again (as you implemented once in the first pr). Is this possible to implement? 
4. Regarding your question on slack, we don’t need to increase the number of Y elements (one is enough) 
5. I didn’t understood the issue regarding the inertial tensor, why do we get a segfault? (We don’t want to have hard coded parts in general). Is it possible to make the calculations beforehand at the initialization part or in the list for the tweakable parameters? 
6. Could you please add a second parameter for the tether thickness such that we can differentiate between the visual thickness and the physical thickness?
7. Please rename cl for tether length otherwise it can be confused for other people as it stands normally for the lift coefficent (e.g. tl and tr for tether length and tether radius)
8. Please add the cda parameter to the tweakable list of parameters. Additionally the drag is not proper calculated. As we have a cylinder and not an airfoil the drag coefficient should be kept constant. What I meant last time, that the drag should be dependent on the angle of attack is not the drag coefficient itself, but the direction of the drag force vector. Thus I would propose to add an if statement (or additional parameter) within the lift drag plugin keeping the drag coefficient constant for a cylinder.… Or how would you implement it? 

One last general question: To validate if the drag force is properly implemented, is it possible to visualize a force vector in real time within gazebo?

So those were a lot of points, thus just let me know if something is not clear. 
Cheers
wrong_attachment_from 2018-05-04 12-24-25

**Comment by TSC21** [comment]
@GabrielKoenig I will be waiting for your merge so I can address the above on the next PR and directly to your KiteX model.

**Comment by TSC21** [comment]
> 2. Please change the current Y tether implementation. Please do not use angle, and element length as parameter, take instead coordinates of the two attachment point in the body reference frame of the aircraft and the high of the triangular of Y tether. At the moment it is not properly implemented (see attached figure, when changing the element length and number of elements (eg. 5elements and 3m length), the end of the tether and Y element is in the nowhere….)

>@GabrielKoenig This is not linear and trivial as it seems. When you import the models into the same sdf file, in this case, `solo_with_tether`, the `tether` model and the `solo` model are independent from each other and you can only set the relative positions of othanne to the other manually. The only way I see this to be possible is to have a jinja generator that would generate the model of tether + aircraft in the same file but without imports, but that implementation is not elegant at all.

@TSC21 I just discussed with Xander and we think it is the best way to have a jinja generator that would generate the model of theter and aircraft. The main reason is, that we want to provide it for the open source community, thus it should be as handy as possible, thus preferable all tweakable parameters should be in one file.  The second reason is, that the tether attachment point coordinate is one of the performance paramtere that needs to be tuned which is hard if its defined in the world frame. The last  reason but not so important one is, that we want to have different take off location. If the tether is always defined relative to the aircrafts body frame we do not need to take care of the proper attachment point.
One thing I am just curious, what would be your elegant solution? (assuming not going directly to the dynamic implementation)

**Comment by TSC21** [comment]
> 3. Referring to 2 it would be desirable that we can also define the location of the anchor point within the set of tweakable parameters. Thus I was thinking of defining the two attachment point on the aircraft and defining the anchor point on the ground (preferably [0;0;0] in the world frame) as fixed input. The jinja generator would generate half of the tether away from the aircraft and come back again (as you implemented once in the first pr). Is this possible to implement?

> This totally depends of what is done on the 2. point. Though I think the last request above is more of a visual feature than an actual performance requirement.

@TSC21 referring to 2, I would also integrate anchor point in the jinja file.

**Comment by TSC21** [comment]
> 5. I didn’t understood the issue regarding the inertial tensor, why do we get a segfault? (We don’t want to have hard coded parts in general). Is it possible to make the calculations beforehand at the initialization part or in the list for the tweakable parameters?

>I still don't have a concrete answer to what is causing this.

@TSC21 then lets skip this task at it doesn't have high priority.

**Comment by TSC21** [comment]
> 6. Could you please add a second parameter for the tether thickness such that we can differentiate between the visual thickness and the physical thickness?

> You have a collision block and the visual block that use this same thickness (`cylinder` with `cr` being the cylinder radius). Any reason for differentiating both?

 @TSC21 the tether is at the moment almost not visible as it is physically so thin. (Its more a visual feature than a performance criterion. )

**Comment by TSC21** [comment]
@GabrielKoenig based on https://github.com/RigidWing/sitl_gazebo/pull/5#issuecomment-388021591 please let me know if it makes sense to you to advance to that approach (have a jinja file generating the whole `kitex_with_tether` file). Will be waiting for your feedback to advance on this.

@TSC21 yes I would advance to this approach.

**Pull request merged**
