### PR TITLE
PR: dynamic tether rebased

### PR DESCRIPTION
**Pull request by TSC21**
@GabrielKoenig @xgerrmann this is the rebased version of #1. It is basically your commits and mine rebased over the current `sitl_gazebo` master, with no other changes. Since you already accepted the changes on #1, can you please merge this PR so to sync your master with the latest changes and so my next PR can already include the jinja sdf generator and other details? This is for a matter of clarity and so to a cleaner implementation over the next iterations. Please, also test your `rigid_wing`/`plane_with_tether` models so it works as expected.

### CODE REVIEW

**Comment by xgerrmann** [comment]
@TSC21 
Hello Nuno,
Thank you for your work!

The tether looks quite realistic, especially near its limit (fully stretched) it behaves realistically.
I have made two recordings on how I have checked your implementation, you can download these via this link: https://we.tl/a3wRG6FJsV.

I have two remarks:
1. You can drop/disable the joint limits. As you see when we keep rotating it will eventually limit the motion of the solo quad. This is undesired behaviour (we do not have a steel cable, but a very flexible thin cable).
2. This is just a small remark. The damping is already much nicer than it was. I think it still needs to be reduced, but as you will now be working on ninja generation you can leave it for what it is now.

@GabrielKoenig I will leave the pull request up to you.

**Comment by TSC21** [comment]
> You can drop/disable the joint limits. As you see when we keep rotating it will eventually limit the motion of the solo quad. This is undesired behaviour (we do not have a steel cable, but a very flexible thin cable).

Yeah it makes sense and we can actually see that behavior specially on the `solo` model flight. I will fix that.

> This is just a small remark. The damping is already much nicer than it was. I think it still needs to be reduced, but as you will now be working on ninja generation you can leave it for what it is now.

Yeah I will create a `.sdf.jinja` file to generate the specific `.sdf` file on compile time and there all of these elements properties can be tweaked.

@xgerrmann thanks for merging. I will now continue from the master branch.

**Comment by TSC21** [comment]
> Regarding the data (3.3), you could also add a force sensor to one of the end joints... (we just need always to have the values printed out (within gazebo gui or console) for the tether length and tether_force (velocity can be kept out).

@GabrielKoenig and what plugin should be printing that in this case?

BTW @xgerrmann @GabrielKoenig what do you think you adding the repo to be inspected by Travis and that way we can actually have Travis doing the CI of this repo? You just have to login in https://travis-ci.org and then add access to Travis to the `RigidWing/sitl_gazebo` repository.

**Comment by GabrielKoenig** [comment]
@TSC21 well I would leave it to you...but I thought about something like this (http://gazebosim.org/tutorials?tut=force_torque_sensor&cat=sensors)

And travis had been added. Could you configure the .travis.yml file, as you probably know the best setting for the integration?

**Comment by TSC21** [comment]
> @TSC21 well I would leave it to you...but I thought about something like this (http://gazebosim.org/tutorials?tut=force_torque_sensor&cat=sensors)

Makes sense. Done here: https://github.com/RigidWing/sitl_gazebo/commit/1a185b3dfb6884f9144d4f6cdf69504b7f827ac6

> And travis had been added. Could you configure the .travis.yml file, as you probably know the best setting for the integration?

All set: https://github.com/RigidWing/sitl_gazebo/commit/2bb4d592cf98510f5e16d398d48782dee1c23e0d. And you can check the builds in https://travis-ci.org/RigidWing/sitl_gazebo.

**Pull request merged**
